### PR TITLE
chore(android): update to 18.3.0

### PR DESCRIPTION
**Pull request by m1ga**
merge https://github.com/tidev/ti.playservices/pull/329 first as it will update the github action 

Release notes: 
* https://developers.google.com/android/guides/releases#january_04_2024
* https://developers.google.com/android/guides/releases#january_22_2024

[ti.playservices-android-18.3.0.zip](https://github.com/tidev/ti.playservices/files/14356951/ti.playservices-android-18.3.0.zip)

### CODE REVIEW

**Comment by hansemannn** [comment]
@m1ga Can you advise if these two PR's are still up to date? I want to add Fido support for play services, but these one should be done first

**Comment by m1ga** [comment]
yes, still fine to merge this one and the other one mentioned above to fix the github actions.
I'm using this one for a while now and it works fine. I saw that there is 18.4.0 already (April 16, 2024) but not tested that one yet

**Comment by hansemannn** [comment]
@m1ga The Android build still fails, it seems like it cannot find the SDK, although `ti sdk install 12.2.1.GA` works locally.

**Comment by m1ga** [comment]
odd..let me check something

**Comment by m1ga** [comment]
fixed :smile: It will use Ti 7 now so it need node 18

**Comment by m1ga** [comment]
and now a Java error. Think the action is out of data again. Will fix that

**Comment by m1ga** [comment]
I've just created a pre-release version so I can link it to the SDK. Then we can push it live together with the next SDK

**Pull request merged**
