### PR TITLE
feat(android): update to 18.1.0

### PR DESCRIPTION
**Pull request by m1ga**
Fixes https://github.com/appcelerator-modules/ti.playservices/issues/229

Update dependencies to 18.1.0 and play-services-location:20.0.0

[ti.playservices-android-18.1.0.zip](https://github.com/tidev/ti.playservices/files/9747532/ti.playservices-android-18.1.0.zip)

### CODE REVIEW

**Comment by m1ga** [comment]
once updated we can update

https://github.com/tidev/titanium_mobile/blob/879be32dbad2962d8bd1d3be5bbaa21a6314f108/support/module/packaged/modules.json#L45-L48

**Comment by jordanbisato** [comment]
Since this PR, a new version of play-services-location was released, with some interesting changes: 

https://developers.google.com/android/guides/releases#june_07_2022

Would be good if you can take a look.

**Comment by m1ga** [comment]
Thanks for the info! I've updated the version but will need to test it again.

base is still the same version (https://mvnrepository.com/artifact/com.google.android.gms/play-services-base)

**Comment by m1ga** [comment]
@hansemannn I've made a draft release: https://github.com/tidev/ti.playservices/releases/tag/untagged-141476f9edb60f96859f if that is fine we can release it so I can update the SDK repo: https://github.com/tidev/titanium_mobile/blob/879be32dbad2962d8bd1d3be5bbaa21a6314f108/support/module/packaged/modules.json#L45-L48

**Pull request merged**
