### PR TITLE
feat(android): update library

### PR DESCRIPTION
**Pull request by m1ga**
SDK master (12.1.0)  is using a newer `com.google.android.gms:play-services-location` library. This will reduce in errors like
```
JNI DETECTED ERROR IN APPLICATION: can't call boolean ti.modules.titanium.geolocation.GeolocationModule.hasLocationPermissions() on instance of ti.modules.titanium.filesystem.FileProxy
```
and
```
A/miga: java_vm_ext.cc:594] JNI DETECTED ERROR IN APPLICATION:
can't call boolean ti.modules.titanium.geolocation.GeolocationModule.hasLocationPermissions() on instance of ti.map.AnnotationProxy
    java_vm_ext.cc:594]     in call to CallBooleanMethodA
    java_vm_ext.cc:594]     from boolean org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(long, java.lang.Object, long, java.lang.String, java.lang.Object, boolean, boolean, int, java.lang.String)
```

`Ti.Geolocation.hasLocationPermissions()` returned undefined, logging it in the SDK shows `true` or `false`.

This update will fix it and it returns `true`/`false` again :+1: 

After this is released we'll need to update `titanium_mobile/support/module/packaged/modules.json`

[ti.playservices-android-18.2.0.zip](https://github.com/tidev/ti.playservices/files/10611884/ti.playservices-android-18.2.0.zip)

### CODE REVIEW

**Comment by hansemannn** [comment]
Happy to merge if we have a few community-side approvals. Also, the tests currently fail?
```
 Error:  :  Could not find all required Titanium Modules:
Error:  :     id: ti.playservices	 version: 18.2.0	 platform: android	 deploy-type: development

**Comment by m1ga** [comment]
minSDK is set to 12.1.0

**Comment by hansemannn** [comment]
Can you change it [here](https://github.com/tidev/ti.playservices/blob/8cc0ec6bb64f5b7eb3b9c348938d22e6ccdddcc6/.github/workflows/android.yml#L64)?

**Comment by m1ga** [comment]
lets see if it works with nightly builds :)

**Comment by m1ga** [comment]
Karma app is waiting for files again. 
Put too many hours in it already. Things to look at (last time I had to update those):
* socket.io module -> karma-app/client -> tests in module

versions are the same as in ti.map now, so the socket version should be compatible with karma-app now. But it doesn't run the test after receiving the files :shrug: 
```
5 02 2023 22:30:46.143:DEBUG [launcher]: Titanium Test Runner (id 59904015) captured in 29.258 secs
05 02 2023 22:30:46.143:DEBUG [undefined 0.0.0 (android 0.0.0)]: CONNECTED -> CONFIGURING
05 02 2023 22:30:46.397:DEBUG [middleware:source-files]: Requesting /base/node_modules/karma-jasmine/lib/boot.js?760d54bbca4f739f1f8b252c1636d76201cc4e88
05 02 2023 22:30:46.398:DEBUG [middleware:source-files]: Fetching /home/miga/tools/ti.playservices/node_modules/karma-jasmine/lib/boot.js
05 02 2023 22:30:46.398:DEBUG [web-server]: serving (cached): /home/miga/tools/ti.playservices/node_modules/karma-jasmine/lib/boot.js
05 02 2023 22:30:46.400:DEBUG [middleware:source-files]: Requesting /base/test/unit/specs/constants.spec.js?5cd73615dafa810b5846fc30340234b47f61b8d0
05 02 2023 22:30:46.400:DEBUG [middleware:source-files]: Fetching /home/miga/tools/ti.playservices/test/unit/specs/constants.spec.js
05 02 2023 22:30:46.400:DEBUG [web-server]: serving (cached): /home/miga/tools/ti.playservices/test/unit/specs/constants.spec.js
05 02 2023 22:30:46.407:DEBUG [middleware:source-files]: Requesting /base/node_modules/karma-jasmine/lib/adapter.js?db55991565c0f0381ab0fb3c340df5194b4bef99
05 02 2023 22:30:46.407:DEBUG [middleware:source-files]: Fetching /home/miga/tools/ti.playservices/node_modules/karma-jasmine/lib/adapter.js
05 02 2023 22:30:46.407:DEBUG [web-server]: serving (cached): /home/miga/tools/ti.playservices/node_modules/karma-jasmine/lib/adapter.js
05 02 2023 22:30:46.408:DEBUG [middleware:source-files]: Requesting /base/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?5a831622ecb7c749ca96e36d473ee583ebf6298b
05 02 2023 22:30:46.408:DEBUG [middleware:source-files]: Fetching /home/miga/tools/ti.playservices/node_modules/jasmine-core/lib/jasmine-core/jasmine.js
05 02 2023 22:30:46.408:DEBUG [web-server]: serving (cached): /home/miga/tools/ti.playservices/node_modules/jasmine-core/lib/jasmine-core/jasmine.js
05 02 2023 22:30:46.409:DEBUG [middleware:source-files]: Requesting /base/test/unit/specs/methods.spec.js?0fe374923b1c4a8877e87725bcf0dad94d23af3e
05 02 2023 22:30:46.409:DEBUG [middleware:source-files]: Fetching /home/miga/tools/ti.playservices/test/unit/specs/methods.spec.js
05 02 2023 22:30:46.409:DEBUG [web-server]: serving (cached): /home/miga/tools/ti.playservices/test/unit/specs/methods.spec.js
05 02 2023 22:30:46.482:DEBUG [undefined 0.0.0 (android 0.0.0)]: CONFIGURING -> EXECUTING
```

and then it stops.

**Comment by m1ga** [comment]
green now, but have to fix something in the SDK later today

**Comment by m1ga** [comment]
so its the node-titanium-sdk update in https://github.com/tidev/titanium_mobile/pull/13724
thats causing issues with the karma tests.

Everything after that PR results in:
```
06 02 2023 10:34:58.348:ERROR [titanium]: TiExceptionHandler: (main) [33,7548]     let lines = error.stack.split('\n').filter(function(line) {
06 02 2023 10:34:58.348:ERROR [titanium]: TiExceptionHandler:                             ^
06 02 2023 10:34:58.348:ERROR [titanium]: TiExceptionHandler: Uncaught TypeError: error.stack.split is not a function
06 02 2023 10:34:58.348:ERROR [titanium]: TiExceptionHandler: new StackTrace (eval at <anonymous> (/titanium-karma-client.js:466:9), <anonymous>:9378:29),callerFile (eval at <anonymous> (/titanium-karma-client.js:466:9), <anonymous>:704:19),Object.eval [as jasmineFile] (eval at <anonymous> (/titanium-karma-client.js:466:9), <anonymous>:713:18),new ExceptionFormatter (eval at <anonymous> (/titanium-karma-client.js:466:9), <anonymous>:3441:51),Object.buildExpectationResult (eval at <anonymous> (/titanium-karma-client.js:466:9), <anonymous>:2573:32),Spec.addExpectationResult (eval at <anonymous> (/titanium-karma-client.js:466:9), <anonymous>:809:34),Spec.handleException (eval at <anonymous> (/titanium-karma-client.js:466:9), <anonymous>:941:10),QueueRunner.onException (eval at <anonymous> (/titanium-karma-client.js:466:9), <anonymous>:879:30),onException (eval at <anonymous> (/titanium-karma-client.js:466:9), <anonymous>:7504:12),handleError (eval at <anonymous> (/titanium-karma-client.js:466:9), <anonymous>:7511:7),EventEmitter.taggedOnError (eval at <anonymous> (/titanium-karma-client.js:466:9), <anonymous>:4005:11),EventEmitter.emit (<embedded>:7465:16),App.<anonymous> (<embedded>:7825:13),App.value (ti:/kroll.js:1430:27),App.value (ti:/kroll.js:1477:25)
```
(error in jasmine-core/lib/jasmine-core/jasmine.js) - error.stack is not a string

Karma-ti-launcher still includes the old version https://github.com/tidev/karma-titanium-launcher/blob/develop/package.json#L30

**Review by hansemannn — APPROVED** [review]

**Pull request merged**
